In [2]:
import numpy as np

In [27]:
ndarr = np.arange(35, 75)
ndarr = ndarr.reshape(10,4) # ndarr.reshape는 결과물을 출력하는 거지 ndarr자체를 바꾸진 않는다
#ndarr.shape = (10,4)
print(ndarr)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [9]:
print(ndarr[::-1]) # 맨 뒤에서부터 행을 통째로 리버스로

array([[71, 72, 73, 74],
       [67, 68, 69, 70],
       [63, 64, 65, 66],
       [59, 60, 61, 62],
       [55, 56, 57, 58],
       [51, 52, 53, 54],
       [47, 48, 49, 50],
       [43, 44, 45, 46],
       [39, 40, 41, 42],
       [35, 36, 37, 38]])

In [35]:
ndarr8 = ndarr[1:9, 2:4] # 1번부터 8번 행 까지, 열은 세번째와 네번째
#ndarr8 = [1:-1, 2:] # 1번부터 끝에서 -1 행까지, 열은 2번부터 끝까지
print(ndarr8)

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [54]:
ndarr9 = ndarr[::, -1]
print(ndarr9)
ndarr9 = ndarr9.reshape(2,5)
print(ndarr9)

[38 42 46 50 54 58 62 66 70 74]
[[38 42 46 50 54]
 [58 62 66 70 74]]


In [55]:
ndarr10 = ndarr9[::-1]
print(ndarr10)

[[58 62 66 70 74]
 [38 42 46 50 54]]


In [41]:
rng = np.random.default_rng(1)

In [45]:
ndarr11 = rng.integers(1,51, (5,6))
print(ndarr11)
print(ndarr11[ndarr11 % 2 == 0])

[[22 26 15  6 22 32]
 [23 39 19 31 39 46]
 [22  2 36 27 44 23]
 [19  4 23 33 39 43]
 [11 30 41 14 18 42]]
[22 26  6 22 32 46 22  2 36 44  4 30 14 18 42]
