In [5]:
import numpy as np

In [11]:
ndarr = np.zeros(10) # 0들로 채워진 새로운 array
print(ndarr)
ndarr[4] = 1 #리스트 처럼 위치 찾아서
print(ndarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
ndarr = np.arange(10,31) # 10 부터 30 까지의 숫자들로 이루어진
print(ndarr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [17]:
ndarr = np.random.randint(0, 100, size=(2,2)) # 사이즈 (2,2)의 0부터 99까지로 이루어진
print(ndarr)
ndarr = np.random.rand(2, 4) # 사이즈 (2,4) 의 0부터 1사이
print(ndarr)

[[54 54]
 [74 52]]
[[0.60554547 0.11810741 0.77698857 0.17485102]
 [0.20678556 0.91913066 0.69281602 0.55405088]]
