In [1]:
import numpy as np

In [7]:
arr = np.array([1, 1, 2, 3, 4, 5, 5, 5, 5, 7, 8, 9, 10, 11, 24 ,100])

arr1 = np.unique(arr)
print("중복 제거: ", arr1)
maximum = np.max(arr1)
minimum = np.min(arr1)
mean = np.mean(arr1)
print(f"최대: {maximum}, 최소: {minimum}, 평균: {mean}")
result = np.sum(arr1)
print(f"합: {result}")

median = np.median(arr) # median은 arr.median()으로 해결이 안됨
print(f"중복 제거 없는 중간값: {median}")

중복 제거:  [  1   2   3   4   5   7   8   9  10  11  24 100]
최대: 100, 최소: 1, 평균: 15.333333333333334
합: 184
중복 제거 없는 중간값: 5.0


In [19]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
print(x)

col1 = x[:, 0] # 0부터 시작하므로 1번은 0
print(col1)
col1_max = np.max(col1)
col1_min = np.min(col1)
col1_mean = np.mean(col1)
print(f"1열의 최대 : {col1_max}, 최소: {col1_min}, 평균: {col1_mean}")
#print(np.max(x, axis=0)[0]) # 요렇게도 가능

row2 = x[1] # 마찬가지로 2번 1
print(row2)
row2_sum = np.sum(row2)
print(f"2행의 합: {row2_sum}")

arr1_arg = np.argsort(arr1)
arr1_arg = arr1_arg[::-1] # 내림차순을 위해 뒤집기
print(arr1_arg)
arr1_sort = arr1[arr1_arg]
print("내림차순: ", arr1_sort)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
[  0 -99 -99]
1열의 최대 : 0, 최소: -99, 평균: -66.0
[-99   6 -99   8 -99]
2행의 합: -283
[11 10  9  8  7  6  5  4  3  2  1  0]
내림차순:  [100  24  11  10   9   8   7   5   4   3   2   1]
