In [2]:
import numpy as np

In [11]:
ndarr = np.zeros(10) # 0들로 채워진 새로운 array
print(ndarr)
ndarr[4] = 1 #리스트 처럼 위치 찾아서
print(ndarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
ndarr = np.arange(10,31) # 10 부터 30 까지의 숫자들로 이루어진
print(ndarr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [5]:
rng = np.random.default_rng() # () 값이 없으면 무조건 랜덤, 안에 값이 있으면 일종의 순서가 있는 시드 생성

In [6]:
ndarr = np.random.randint(0, 100, size=(2,2)) # 사이즈 (2,2)의 0부터 99까지로 이루어진
an4_2 = rng.integers(0,100, (2,2))
print(an4_2)
print(ndarr)
ndarr = np.random.rand(2, 4) # 사이즈 (2,4) 의 0부터 1사이
print(ndarr)

[[43  0]
 [68 66]]
[[93 78]
 [95 57]]
[[0.99048766 0.05334481 0.91488462 0.966147  ]
 [0.74932609 0.64500597 0.91103641 0.3720525 ]]
