In [1]:
print("Hello world!")

Hello world!


In [ ]:
import numpy as np # numpy import

In [4]:
a = 1
a

1

In [5]:
b = [1, 2, 3, 4, 5]
b

[1, 2, 3, 4, 5]

In [6]:
print(b*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [9]:
import os, time, random
if os.path.exists("./Answer/12_12/word.txt"): #특정 파일이 현재 경로에 있다면
    with open("./Answer/12_12/word.txt", "r") as f:
        word = f.read().split() #한칸 띄어쓰기 기준으로 쪼개기
        # data = f.readlines()
        print(word) # word는 지역변수가 아니라 글로벌이어서 밑에서 사용 가능
else:  #없다면 리스트를 하나 여기서 만듬
    word = ['sky', 'earth', 'moon', 'flower', 'tree', 'apple',
            'grape', 'garlic', 'onion', 'potato']

n = 1 # 1번 문제부터

input("타자게임이 준비되었을 경우 아무키 입력")
start = time.time() # 타이머 시작

while n < 11 :
    print("문제", n)
    question = random.choice(word) #word 중에 랜덤으로 추첨
    print(question)
    user = input()
    if question == user : # 문제와 답이 일치한다면
        print("통과!")
        n += 1
    else :
        print("오타! 다시 도전")

end = time.time() #종료 시간 확인
et = end - start
print(f"타자 시간: {et: .2f}") #et를 소수점 2자리까지 표시

['sky', 'earth', 'moon', 'flower', 'tree', 'apple', 'grape', 'garlic', 'onion', 'potato']
문제 1
apple
통과!
문제 2
tree
통과!
문제 3
garlic
통과!
문제 4
tree
오타! 다시 도전
문제 4
flower
통과!
문제 5
sky
오타! 다시 도전
문제 5
tree
통과!
문제 6
flower
통과!
문제 7
moon
통과!
문제 8
potato
통과!
문제 9
earth
통과!
문제 10
potato
오타! 다시 도전
문제 10
sky
오타! 다시 도전
문제 10
apple
오타! 다시 도전
문제 10
potato
오타! 다시 도전
문제 10
onion
통과!
타자 시간:  56.38


In [5]:
import numpy as np
x = np.array([3,1,2,'a']) # a와 숫자가 같이 있다면 한가지 형태만 인정. 그래서 모두 string
print(x)
print([3,1,2,'a'])
print(type(x))
print(type([3,1,2]))

['3' '1' '2' 'a']
[3, 1, 2, 'a']
<class 'numpy.ndarray'>
<class 'list'>


In [10]:
c = [[1], [1,2]]
d = np.array([[1,3],[1,2]]) #np는 array의 차원, 갯수가 같아야 한다

for x,y in d:
    print(x,y)

1 3
1 2


In [11]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 5.0, 6.0])

print(x+y) # 행렬 연산
print(x-y) # 연산하려면 같은 차원 유지
print(x*y)
print(x/y)

[3. 7. 9.]
[-1. -3. -3.]
[ 2. 10. 18.]
[0.5 0.4 0.5]


In [21]:
#print(x.shape) #차원 형태
#print(x.dtype) #data type
#print(d.shape)
#print(y/2.0)
d.ndim
d.shape

(2, 2)

In [22]:
a = np.array([[1,2], [3,4], [5,6]])
print(a.ndim)
print(a.shape)

2
(3, 2)


In [23]:
a = np.array([[[1],[2]], [[3], [4]], [[5], [6]]])
print(a.ndim) # 3차원
print(a.shape) # 안에 3개 들어있고 그 안에 2개, 그 안에 1개

3
(3, 2, 1)


In [24]:
a = np.array([[[1,2],[2,2]], [[3,2], [4,2]], [[5,2], [6,2]]]) # 색깔 3개 = 3차원!
print(a.ndim) # 3차원
print(a.shape) # 안에 3개 들어있고 그 안에 2개, 그 안에 2개

3
(3, 2, 2)


In [25]:
np.dot(4, 2)


8

In [26]:
ndar1 = np.array([1,2])
ndar2 = np.array([4,6])
np.dot(ndar1, ndar2)

16

In [27]:
ndar1 = np.array([[1,2], [3,4]])
ndar2 = np.array([[1,2], [3,4]])
np.dot(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [30]:
ndar1 = np.array([[1,2], [3,4]])
ndar2 = np.array([[1,2], [3,4]])
np.matmul(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [35]:
ndar1 = np.array([[1,2], [3,4]])
print(ndar1.flatten()) # 1차원으로 평탄화 시킴

ndar2 = np.array([[[1],[2],[3]]])
print(ndar2.flatten()) # 1차원으로 평탄화 시킴
print(ndar2) #ndar2는 바뀌지 않음. flatten은 바뀐거를 리턴하는거지 ndar2를 바꾸진 않음

[1 2 3 4]
[1 2 3]
[[[1]
  [2]
  [3]]]


In [38]:
ndarr = np.array([[1,2], [2,3], [3,4]])
print(ndarr.reshape(2,3)) # (3,2)를 (2,3) 로 바꾸기
#ndarr.reshape(2, 4) # 3*2 = 6개인데 8개 짜리로는 바꿀 수 없다
print(ndarr.reshape(1,6)) # 6개니까 (1,6)도 가능

[[1 2 2]
 [3 3 4]]
[[1 2 2 3 3 4]]


In [44]:
np.random.randint(1, 5, size=(2,4)) #(2,4) 사이즈의 1부터 4까지 랜덤 숫자
np.random.rand(5) # (1,5) 사이즈의 0~1 사이의 랜덤 숫자

array([0.80012837, 0.70539318, 0.40179481, 0.83881108, 0.9431511 ])

In [47]:
rng =np.random.default_rng()
print(rng.random()) # 최신 동향은 rng를 활용하는 형태로
print(rng.integers(0, 10, (2,4))) # 0 부터 9까지 (2,4) 사이즈로

0.6450490207514177
[[4 5 4 3]
 [2 5 8 4]]


In [50]:
ndarr = np.array([[6,3], [5,2], [4,1]])
print(ndarr > 4)

[[ True False]
 [ True False]
 [False False]]


In [52]:
print(ndarr[ndarr > 4]) # 이렇게 해서 안에서 4보다 큰걸, True 값만 나오는걸 뽑아내기
print(ndarr) # ndarr 값을 바꾸는건 아님

[6 5]
[[6 3]
 [5 2]
 [4 1]]
