In [1]:
print("Hello world!")

Hello world!


In [2]:
import numpy as np # numpy import
import pandas as pd # pandas import

In [4]:
a = 1
a

1

In [5]:
b = [1, 2, 3, 4, 5]
b

[1, 2, 3, 4, 5]

In [6]:
print(b*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [9]:
import os, time, random
if os.path.exists("./Answer/12_12/word.txt"): #특정 파일이 현재 경로에 있다면
    with open("./Answer/12_12/word.txt", "r") as f:
        word = f.read().split() #한칸 띄어쓰기 기준으로 쪼개기
        # data = f.readlines()
        print(word) # word는 지역변수가 아니라 글로벌이어서 밑에서 사용 가능
else:  #없다면 리스트를 하나 여기서 만듬
    word = ['sky', 'earth', 'moon', 'flower', 'tree', 'apple',
            'grape', 'garlic', 'onion', 'potato']

n = 1 # 1번 문제부터

input("타자게임이 준비되었을 경우 아무키 입력")
start = time.time() # 타이머 시작

while n < 11 :
    print("문제", n)
    question = random.choice(word) #word 중에 랜덤으로 추첨
    print(question)
    user = input()
    if question == user : # 문제와 답이 일치한다면
        print("통과!")
        n += 1
    else :
        print("오타! 다시 도전")

end = time.time() #종료 시간 확인
et = end - start
print(f"타자 시간: {et: .2f}") #et를 소수점 2자리까지 표시

['sky', 'earth', 'moon', 'flower', 'tree', 'apple', 'grape', 'garlic', 'onion', 'potato']
문제 1
apple
통과!
문제 2
tree
통과!
문제 3
garlic
통과!
문제 4
tree
오타! 다시 도전
문제 4
flower
통과!
문제 5
sky
오타! 다시 도전
문제 5
tree
통과!
문제 6
flower
통과!
문제 7
moon
통과!
문제 8
potato
통과!
문제 9
earth
통과!
문제 10
potato
오타! 다시 도전
문제 10
sky
오타! 다시 도전
문제 10
apple
오타! 다시 도전
문제 10
potato
오타! 다시 도전
문제 10
onion
통과!
타자 시간:  56.38


In [5]:
import numpy as np
x = np.array([3,1,2,'a']) # a와 숫자가 같이 있다면 한가지 형태만 인정. 그래서 모두 string
print(x)
print([3,1,2,'a'])
print(type(x))
print(type([3,1,2]))

['3' '1' '2' 'a']
[3, 1, 2, 'a']
<class 'numpy.ndarray'>
<class 'list'>


In [10]:
c = [[1], [1,2]]
d = np.array([[1,3],[1,2]]) #np는 array의 차원, 갯수가 같아야 한다

for x,y in d:
    print(x,y)

1 3
1 2


In [11]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 5.0, 6.0])

print(x+y) # 행렬 연산
print(x-y) # 연산하려면 같은 차원 유지
print(x*y)
print(x/y)

[3. 7. 9.]
[-1. -3. -3.]
[ 2. 10. 18.]
[0.5 0.4 0.5]


In [21]:
#print(x.shape) #차원 형태
#print(x.dtype) #data type
#print(d.shape)
#print(y/2.0)
d.ndim
d.shape

(2, 2)

In [22]:
a = np.array([[1,2], [3,4], [5,6]])
print(a.ndim)
print(a.shape)

2
(3, 2)


In [23]:
a = np.array([[[1],[2]], [[3], [4]], [[5], [6]]])
print(a.ndim) # 3차원
print(a.shape) # 안에 3개 들어있고 그 안에 2개, 그 안에 1개

3
(3, 2, 1)


In [24]:
a = np.array([[[1,2],[2,2]], [[3,2], [4,2]], [[5,2], [6,2]]]) # 색깔 3개 = 3차원!
print(a.ndim) # 3차원
print(a.shape) # 안에 3개 들어있고 그 안에 2개, 그 안에 2개

3
(3, 2, 2)


In [25]:
np.dot(4, 2)


8

In [26]:
ndar1 = np.array([1,2])
ndar2 = np.array([4,6])
np.dot(ndar1, ndar2)

16

In [27]:
ndar1 = np.array([[1,2], [3,4]])
ndar2 = np.array([[1,2], [3,4]])
np.dot(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [30]:
ndar1 = np.array([[1,2], [3,4]])
ndar2 = np.array([[1,2], [3,4]])
np.matmul(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [35]:
ndar1 = np.array([[1,2], [3,4]])
print(ndar1.flatten()) # 1차원으로 평탄화 시킴

ndar2 = np.array([[[1],[2],[3]]])
print(ndar2.flatten()) # 1차원으로 평탄화 시킴
print(ndar2) #ndar2는 바뀌지 않음. flatten은 바뀐거를 리턴하는거지 ndar2를 바꾸진 않음

[1 2 3 4]
[1 2 3]
[[[1]
  [2]
  [3]]]


In [38]:
ndarr = np.array([[1,2], [2,3], [3,4]])
print(ndarr.reshape(2,3)) # (3,2)를 (2,3) 로 바꾸기
#ndarr.reshape(2, 4) # 3*2 = 6개인데 8개 짜리로는 바꿀 수 없다
print(ndarr.reshape(1,6)) # 6개니까 (1,6)도 가능

[[1 2 2]
 [3 3 4]]
[[1 2 2 3 3 4]]


In [44]:
np.random.randint(1, 5, size=(2,4)) #(2,4) 사이즈의 1부터 4까지 랜덤 숫자
np.random.rand(5) # (1,5) 사이즈의 0~1 사이의 랜덤 숫자

array([0.80012837, 0.70539318, 0.40179481, 0.83881108, 0.9431511 ])

In [47]:
rng =np.random.default_rng()
print(rng.random()) # 최신 동향은 rng를 활용하는 형태로
print(rng.integers(0, 10, (2,4))) # 0 부터 9까지 (2,4) 사이즈로

0.6450490207514177
[[4 5 4 3]
 [2 5 8 4]]


In [50]:
ndarr = np.array([[6,3], [5,2], [4,1]])
print(ndarr > 4)

[[ True False]
 [ True False]
 [False False]]


In [52]:
print(ndarr[ndarr > 4]) # 이렇게 해서 안에서 4보다 큰걸, True 값만 나오는걸 뽑아내기
print(ndarr) # ndarr 값을 바꾸는건 아님

[6 5]
[[6 3]
 [5 2]
 [4 1]]


In [2]:
#12.14
a = np.array([[1,2], [3,4]])
expanded = np.expand_dims(a, 0)
print(expanded)
print(expanded.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [3]:
expanded = np.expand_dims(a, 1)
print(expanded)
print(expanded.shape)

[[[1 2]]

 [[3 4]]]
(2, 1, 2)


In [ ]:
[[[1 2]]

 [[3 4]]]

In [4]:
expanded = np.expand_dims(a, 2)
print(expanded)
print(expanded.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [9]:
np_ones = np.ones((1,2,1,3))
print(np_ones)
print(np_ones.shape)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
(1, 2, 1, 3)


In [6]:
squeezed = np.squeeze(np_ones)
print(squeezed)
print(squeezed.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [7]:
squeezed = np.squeeze(np_ones, 0)
print(squeezed)
print(squeezed.shape)

[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)


In [8]:
squeezed = np.squeeze(np_ones, 2)
print(squeezed)
print(squeezed.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)


In [10]:
a = [1,2,2,3,3,3,4,4]
unique_a, indexes, counts = np.unique(a, return_counts= True, return_index= True) #counts 보다 index가 먼저 출력됨
print(unique_a, counts, indexes)

[1 2 3 4] [1 2 3 2] [0 1 3 6]


In [22]:
a = np.array([1,4,2,3])
b = np.sort(a) # a[np.argsort(a)]
print(f"a {a}")
print(f"b {b}")
c = np.argsort(a) # [0,2,3,1] 1은 원래 0번쨰, 2는 원래 2번째, 3은 원래 3번째, 4는 원래 1번째
print(f"c {c}")
print(f"cc {a[c]}")
print(f"a {a}")
a[c.sort()]

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a [1 4 2 3]
None


array([[1, 4, 2, 3]])

In [23]:
a = np.array([1,4,2,3])
result = np.mean(a)
print(result)
result = np.std(a)
print("mean ", result)
result = np.var(a)
print("분산 ",result)
result = np.max(a)
print("max",result)
result = np.min(a)
print("min",result)
result = np.sum(a)
print("sum",result)
result = np.prod(a)
print("prod",result)
result = np.median(a)
print("median",result)

2.5
1.118033988749895
1.25
4
1
10
24
2.5


In [2]:
#12.16
import pandas as pd

In [3]:
growth = pd.Series([143, 150, 157, 160], index=["2018","2019","2020","2021"]) # 판다스로 각 값마다 2018년과 같은 index가 부여된 array를 생성
growth # 인덱스 지정이 없으면 다른 리스트 처럼 0,1,2,3 이런식으로 인덱스 지정

2018    143
2019    150
2020    157
2021    160
dtype: int64

In [5]:
index=["2018","2019","2020","2021"]
Yeounghee = pd.Series([143, 150, 157, 160], index=index) #데이터를 Series로 먼저 지정하고 넣는 방법
Chelosu = pd.Series([165, 172, 1175, 180]   , index=index) 

growth = pd.DataFrame({
    "영희" : Yeounghee,
    "철수" : Chelosu
})

growth

영희    철수
2018  143   165
2019  150   172
2020  157  1175
2021  160   180

In [6]:
index=["2018","2019","2020","2021"]
data = {
    "영희" : [143, 150, 157, 160],
    "철수" : [165, 172, 1175, 180]
}

growth = pd.DataFrame(data, index = index) # 데이터를 바로 넣는 방법
growth

영희    철수
2018  143   165
2019  150   172
2020  157  1175
2021  160   180

In [8]:
growth.astype({"영희" : "float"}) #영희라는 column의 값을 float 타입으로 바꾸기

영희    철수
2018  143.0   165
2019  150.0   172
2020  157.0  1175
2021  160.0   180

In [9]:
print(growth) # astype은 잠깐만 타입을 바꿔줌

       영희    철수
2018  143   165
2019  150   172
2020  157  1175
2021  160   180


In [13]:
pd.read_csv("./input/1.csv") # 특정 경로의 csv 파일 읽어들이기

A   B  C
0  30  21  9

In [14]:
pd.read_csv("./input/2.csv", index_col=0) # 특정 column을 index 열로 지정함

A   B  C
0    30  21  9
100   2   3  1

In [ ]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

animals.to_csv("./output/cows_and_goats.csv") # 이 경로에 animal의 내용이 담긴 csv 파일을 생성함

In [17]:
growth["영희"]

2018    143
2019    150
2020    157
2021    160
Name: 영희, dtype: int64

In [18]:
growth.영희

2018    143
2019    150
2020    157
2021    160
Name: 영희, dtype: int64

In [19]:
growth["영희"][0]

C:\Users\USER\AppData\Local\Temp\ipykernel_11984\2659709295.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  growth["영희"][0]


143

In [20]:
growth.iloc[0] # 0번째 row 값들 반환

영희    143
철수    165
Name: 2018, dtype: int64

In [21]:
growth.iloc[1]

영희    150
철수    172
Name: 2019, dtype: int64

In [23]:
growth.iloc[:2, :2] # 숫자들을 사용하여 위치 찾기 가능

영희   철수
2018  143  165
2019  150  172

In [24]:
growth.loc['2020', '영희'] # 특정 index값의 column값을 출력 가능

157

In [25]:
growth.loc["2021"] # 숫자 대신에 index로 주어진 label 기반으로 값 찾기 가능

영희    160
철수    180
Name: 2021, dtype: int64

In [26]:
growth.loc[:, "영희"]

2018    143
2019    150
2020    157
2021    160
Name: 영희, dtype: int64

In [27]:
growth.loc[:, ["영희","철수"]]

영희    철수
2018  143   165
2019  150   172
2020  157  1175
2021  160   180

In [28]:
growth.loc[["2018", "2020"], ["영희","철수"]] # 건너 뛰기도 가능

영희    철수
2018  143   165
2020  157  1175

In [32]:
growth.loc["2018" : "2020", "영희" : "철수"] #이렇게 하면 2018에서 2020까지를. loc는 ~까지에서 뒤에 값을 포함하고 있음

영희    철수
2018  143   165
2019  150   172
2020  157  1175

In [33]:
growth.set_index("영희") # 영희 column을 인덱스로 써서 출력. 영구적인건 아님

철수
영희       
143   165
150   172
157  1175
160   180

In [34]:
growth.loc[growth.영희 > 150] # 영희가 150 이상일때를 모두 가져오기

영희    철수
2020  157  1175
2021  160   180

In [3]:
index = ["영희", "철수", "영철"]
data = {
    "2018" : [143, 165, 157],
    "2019" : [150, 172, 177],
    "2020" : [157,175,180]
}

growth = pd.DataFrame(data, index = index) # 가로 세로 바꾸는 명령어는 읎고 아예 새로 짤때 index랑 data 바꿔주기
growth

2018  2019  2020
영희   143   150   157
철수   165   172   175
영철   157   177   180

In [39]:
growth["2018"] > 150 # 2018년도에 철수와 영철은 넘었고 영희는 아니었다

영희    False
철수     True
영철     True
Name: 2018, dtype: bool

In [42]:
growth.loc[(growth["2018"] > 150) & (growth["2020"] > 150)] # & = and, | = or, isin([list]) = 이중에 있다면, index.notnull = 이 index에 null 값이 없는것만 선택

2018  2019  2020
철수   165   172   175
영철   157   177   180

In [46]:
growth["2021"] = 140 # 2021이라는 column의 각 row들에 140이라는 값을 넣음
growth

2018  2019  2020  2021
영희   143   150   157   140
철수   165   172   175   140
영철   157   177   180   140

In [5]:
#12.17
print(growth["2018"].idxmax()) # 2018년도의 숫자가 가장 큰 인덱스
print(growth["2018"].idxmin()) # 2018년도의 숫자가 가장 작은 인덱스

철수
영희


In [12]:
def check(row):
    if row["영희"] > 160 :
        return 2
    elif row["영희"] > 150 :
        return 1
    else :
        return 0

In [13]:
growth.apply(check, axis="index") # axis에 index, row, column등 지정 가능
#growth.apply(check, axis="index") # axis에 columns를 넣으면 오류발생

2018    0
2019    0
2020    1
dtype: int64

In [ ]:
index = ["영희", "철수", "영철", "순자"]
data {
    "나이" : [20, 20, 21, 20],
    "지역" : ["대구", "서울", "서울", "서울"],
    "키" : [175, 157, 180, 165]
}